// Uebung2Userman/usermanAng/src/app/edit-user-modal/edit-user-modal.component.ts
import { Component, OnInit } from '@angular/core';
import {NgbActiveModal} from "@ng-bootstrap/ng-bootstrap";

@Component({
  selector: 'app-edit-user-modal',
  templateUrl: './edit-user-modal.component.html',
  styleUrls: ['./edit-user-modal.component.css']
})
export class EditUserModalComponent implements OnInit {

  public firstName: string;
  public lastName: string;

  constructor(public activeModal: NgbActiveModal) {
    this.firstName = '';
    this.lastName = '';
  }

  save(): void{
    if(this.lastName.trim().length > 0 && this.firstName.trim().length > 0){
      this.activeModal.close([this.firstName, this.lastName]);
    }
  }

  ngOnInit(): void {
  }

}

<div class="modal-header">
  <h4 class="modal-title">New User</h4>
  <button type="button" class="close" aria-label="Close" (click)="activeModal.dismiss()">
    <span aria-hidden="true">&times;</span>
  </button>
</div>
<div class="modal-body">
  <div class="form-group">
    <label for="firstNameInput">First Name</label>
    <input type="text" class="form-control" id="firstNameInput" [(ngModel)]="firstName">
  </div>
  <div class="form-group">
    <label for="lastNameInput">Last Name</label>
    <input type="text" class="form-control" id="lastNameInput" [(ngModel)]="lastName">
  </div>
</div>
<div class="modal-footer">
  <button type="button" class="btn btn-outline-dark" (click)="activeModal.dismiss()">Schließen</button>
  <button type="button" class="btn btn-success" (click)="save()">Speichern</button>
</div>

// userman-react/src/Components/EditUserModal.tsx
import React from "react";
import {Button, Modal} from 'react-bootstrap';

export default class EditUserModal extends React.Component<any, any> {

    constructor(props: any) {
        super(props);

        this.state = {
            id: 0,
            firstname: '',
            lastname: '',
            description: '',
            show: false
        };

        this.show = this.show.bind(this);
        this.close = this.close.bind(this);
        this.save = this.save.bind(this);
        this.changeDescription = this.changeDescription.bind(this);
        this.changeFirstname = this.changeFirstname.bind(this);
        this.changeFirstname = this.changeFirstname.bind(this);
    }

    show() {
        this.setState({show: true});
    }

    close() {
        this.setState({show: false});
    }

    save() {
        if (this.state.lastname.trim().length > 0 && this.state.firstname.trim().length > 0) {
            this.props.data.editUser(this.state.firstname, this.state.lastname, this.state.id, this.state.description);
            this.props.handleServiceChange();
            this.close();
        }
    }

    changeFirstname = (event: any) => this.setState({firstname : event.target.value});
    changeLastname = (event: any) => this.setState({lastname : event.target.value});
    changeDescription = (event: any) => this.setState({description : event.target.value});

    render() {
        return <Modal show={this.state.show} onHide={this.close}>
            <Modal.Header closeButton>
                <Modal.Title>Edit User</Modal.Title>
            </Modal.Header>

            <Modal.Body>
                <div className="form-group">
                    <label>ID</label>
                    <input className="form-control" type="text" disabled value={this.state.id}/>

                    <label>Firstname</label>
                    <input className="form-control" type="text" onChange={this.changeFirstname} value={this.state.firstname}/>

                    <label>Lastname</label>
                    <input className="form-control" type="text" onChange={this.changeLastname} value={this.state.lastname}/>

                    <label>Description</label>
                    <input className="form-control" type="text" onChange={this.changeDescription} value={this.state.description}/>
                </div>
            </Modal.Body>

            <Modal.Footer>
                <Button variant="secondary" onClick={this.close}>
                    Close
                </Button>
                <Button variant="primary" onClick={this.save}>
                    Save Changes
                </Button>
            </Modal.Footer>
        </Modal>
    }
}
