// Uebung3/userman_vue/src/components/UserTable.vue
<template>
    <div class="container">
      <table class="table table-lined">
        <thead class="thead-light">
        <tr>
          <th scope="col">#</th>
          <th scope="col">First Name</th>
          <th scope="col">Last Name</th>
          <th scope="col">Description</th>
          <th scope="col"></th>
        </tr>
        </thead>
        <tbody>
        <tr v-for="user in users" v-bind:key="user.id" >
            <td>{{user.id}}</td>
            <td>{{user.firstName}}</td>
            <td>{{user.lastName}}</td>
            <td>{{user.description}}</td>
            <td class="text-right">
              <button type="button" class="btn btn-outline-dark btn-sm edit-user-button mr-4" v-on:click="$emit('delete', user.id)">
                Delete
              </button>
              <button type="button" class="btn btn-outline-dark btn-sm edit-user-button mr-4" v-on:click="openEditModal(user)">
                Edit
              </button>
            </td>
        </tr>
        </tbody>
      </table>
      <EditModal v-bind:modalClosed="modalClosed"/>
    </div>
</template>

<script lang="ts">
import Vue from 'vue';
import { User } from '../model/User';
import EditModal from "@/components/EditModal.vue";

export default Vue.extend( {
  name: "UserTable",
  components: {EditModal},
  props: {
    users: Array,
  },
  data(){
    return{
      modalClosed: true,
    }
  },
  methods: {
    openEditModal(user: User){
      console.log(user.id);
      this.modalClosed = false;
    }


  }
})
</script>

<style scoped>

</style>

// Uebung3/userman_react/src/components/UserTable.tsx
import {User} from "../model/User";
import {Table} from 'react-bootstrap';


function UserTable(props: {userList: User[], onDelete: (user: User) => void}){
    const rows = props.userList.map((user) => (
        <tr key={user.id}>
            <td>{user.id}</td>
            <td>{user.firstName}</td>
            <td>{user.lastName}</td>
            <td>{user.description}</td>
            <td>
                <button className="btn btn-outline-danger btn-sm edit-user-button mr-4" onClick={() => props.onDelete(user)}>
                    Delete
                </button>
                <button className="btn btn-outline-light++ btn-sm edit-user-button mr-4">
                    Edit
                </button>
            </td>
        </tr>
    ));

    return (
        <Table striped bordered hover variant="dark">
            <thead>
            <tr>
                <th>#</th>
                <th>Vorname</th>
                <th>Nachname</th>
                <th>Beschreibung</th>
                <th></th>
            </tr>
            </thead>
            <tbody>
            {rows}
            </tbody>
        </Table>
    );
}

export default UserTable;
