// Uebung_2/userman/client/src/app/create-user/create-user.component.ts
import {Component, OnInit} from '@angular/core';
import {DataService} from "../data.service";

@Component({
  selector: 'app-create-user',
  templateUrl: './create-user.component.html',
  styleUrls: ['./create-user.component.css']
})
export class CreateUserComponent implements OnInit {
  user: any = {};
  constructor(private dataService: DataService) {
  }

  ngOnInit(): void {
  }

  saveUser(){
    if (this.user.username.trim().length > 0){
      this.dataService.addUser(this.user);
      this.clearInput()
    }
  }

  clearInput(){
    this.user = {};
  }

}

<form class="p-4">
<h5>Nutzer hinzufügen</h5>
  <div class="form-group">
<label for="firstName">Vorname</label>
<input type="text" id="firstName" class="form-control" [(ngModel)]="user.firstName">
<label for="lastName">Nachname</label>
<input type="text" id="lastName" class="form-control" [(ngModel)]="user.lastName">
  </div>
  <div class="form-group"></div>
<label for="username">Username</label>
<input type="text" id="username" class="form-control" [(ngModel)]="user.username">
<label for="password">Passwort</label>
<input type="password" id="password" class="form-control" [(ngModel)]="user.password">
<label for="description">Beschreibung</label>
<input type="text" id="description" class="form-control" [(ngModel)]="user.description">
<button type="button" class="btn btn-outline-dark" (click)="saveUser(); clearInput()">Hinzufügen</button>

</form>

// Übung 3/vue-usermanager/src/components/CreateUser.vue
<template>
  <form class="p-4">
    <h5>Nutzer hinzufügen</h5>
    <div class="form-group">
      <label for="firstName">Vorname</label>
      <input type="text" id="firstName" class="form-control" v-model="user.firstName">
      <label for="lastName">Nachname</label>
      <input type="text" id="lastName" class="form-control" v-model="user.lastName">
    </div>
    <div class="form-group"></div>
    <label for="description">Beschreibung</label>
    <textarea id="description" class="form-control" v-model="user.description"></textarea>
    <button type="button" class="btn btn-outline-dark" v-on:click="$emit('create-user', user); clear();">Hinzufügen</button>
  </form>
</template>

<script>
export default {
  name: "CreateUser",
  data() {
    return {
      user: {}
    }
  },
  methods: {
    clear: function (){
      this.user = {}
    }
  }
}
</script>

<style scoped>

</style>
