// userman-vue/src/components/UserList.vue
<template>
  <div class="row ml-4 mr-4">
    <div class="col">
      <table class="table table-striped">
        <thead class="thead-light">
        <tr>
          <th scope="col">#</th>
          <th scope="col">First name</th>
          <th scope="col">Last name</th>
          <th scope="col">Username</th>
          <th scope="col">Description</th>
          <th scope="col">Creation</th>
          <th scope="col">Action</th>
        </tr>
        </thead>
        <tbody v-for="item in dataService.userList" v-bind:key="item.id" id="user-table-body">
        <tr id="userID(${user.id})">
          <td>{{ item.id }}</td>
          <td>{{ item.firstName }}</td>
          <td>{{ item.lastName }}</td>
          <td>{{ item.username }}</td>
          <td>{{ item.description }}</td>
          <td>{{ item.creationTime | formatDate }}</td>
          <td id="buttons">
            <button v-on:click="editBtn(item)" v-if="!item.isBlocked" class="btn btn-sm mr-4">
              <svg class="bi bi-pencil-square" fill="currentColor" height="16" viewBox="0 0 16 16"
                   width="16" xmlns="http://www.w3.org/2000/svg">
                <path
                    d="M15.502 1.94a.5.5 0 0 1 0 .706L14.459 3.69l-2-2L13.502.646a.5.5 0 0 1 .707 0l1.293 1.293zm-1.75 2.456-2-2L4.939 9.21a.5.5 0 0 0-.121.196l-.805 2.414a.25.25 0 0 0 .316.316l2.414-.805a.5.5 0 0 0 .196-.12l6.813-6.814z"/>
                <path
                    d="M1 13.5A1.5 1.5 0 0 0 2.5 15h11a1.5 1.5 0 0 0 1.5-1.5v-6a.5.5 0 0 0-1 0v6a.5.5 0 0 1-.5.5h-11a.5.5 0 0 1-.5-.5v-11a.5.5 0 0 1 .5-.5H9a.5.5 0 0 0 0-1H2.5A1.5 1.5 0 0 0 1 2.5v11z"
                    fill-rule="evenodd"/>
              </svg>
            </button>
            <button v-on:click="deleteBtn(item.id)" v-if="!item.isBlocked" class="btn btn-sm">
              <svg class="bi bi-trash2-fill" fill="currentColor" height="16" viewBox="0 0 16 16" width="16"
                   xmlns="http://www.w3.org/2000/svg">
                <path
                    d="M2.037 3.225A.703.703 0 0 1 2 3c0-1.105 2.686-2 6-2s6 .895 6 2a.702.702 0 0 1-.037.225l-1.684 10.104A2 2 0 0 1 10.305 15H5.694a2 2 0 0 1-1.973-1.671L2.037 3.225zm9.89-.69C10.966 2.214 9.578 2 8 2c-1.58 0-2.968.215-3.926.534-.477.16-.795.327-.975.466.18.14.498.307.975.466C5.032 3.786 6.42 4 8 4s2.967-.215 3.926-.534c.477-.16.795-.327.975-.466-.18-.14-.498-.307-.975-.466z"/>
              </svg>
            </button>
            <svg v-if="item.isBlocked" class="bi bi-lock-fill" fill="currentColor" height="16" viewBox="0 0 16 16"
                 width="16"
                 xmlns="http://www.w3.org/2000/svg">
              <path
                  d="M8 1a2 2 0 0 1 2 2v4H6V3a2 2 0 0 1 2-2zm3 6V3a3 3 0 0 0-6 0v4a2 2 0 0 0-2 2v5a2 2 0 0 0 2 2h6a2 2 0 0 0 2-2V9a2 2 0 0 0-2-2z"/>
            </svg>
          </td>
        </tr>
        </tbody>
      </table>
    </div>
    <EditUserModal ref="modal"/>
  </div>
</template>

<script lang="ts">
import {DataService} from "@/model/DataService";
import {Component, Inject, Vue} from "vue-property-decorator";
import EditUserModal from "@/components/EditUserModal.vue";
import {User} from "@/model/User";
import {AlertService} from "@/model/AlertService";

@Component({
  components: {
    EditUserModal
  }
})
export default class UserList extends Vue {
  @Inject("alertService") alertService !: AlertService;
  @Inject("dataService") dataService!: DataService;

  editBtn(user: User) {
    const modal: any = this.$refs.modal;
    modal.id = user.id;
    modal.firstname = user.firstName;
    modal.lastname = user.lastName;
    modal.description = user.description;
    modal.show();
  }

  deleteBtn(id: number) {
    this.dataService.deleteUser(id);
    this.alertService.add("User deleted");
  }
}

</script>

<style scoped>

</style>

// Userman with Angular/src/app/Components/user-list/user-list.component.ts
import {Component, OnInit} from '@angular/core';
import {DataService} from '../../Service/data.service';
import {NgbModal} from '@ng-bootstrap/ng-bootstrap';
import {EditUserModalComponent} from '../edit-user-modal/edit-user-modal.component';
import {DeleteUserModalComponent} from '../delete-user-modal/delete-user-modal.component';
import {Location} from '@angular/common';
import {User} from '../../Model/User';
import {ActivatedRoute} from '@angular/router';
import {WebsocketsService} from '../../Service/websockets.service';

@Component({
  selector: 'app-user-list',
  templateUrl: './user-list.component.html',
  styleUrls: ['./user-list.component.css']
})
export class UserListComponent implements OnInit {

  editPath: string = '/edit/';
  normalPath: string = '/userlist';

  constructor(
    public dataService: DataService,
    private ngbModal: NgbModal,
    private location: Location,
    private route: ActivatedRoute,
    private websocketsService: WebsocketsService
  ) {
    route.params.subscribe(params => {
      if (location.path().includes(this.editPath)) {
        this.editBtn(params.id).then();
      }
    });
  }

  ngOnInit(): void {
  }

  async editBtn(id: number): Promise<void> {
    this.location.go(this.editPath + id);
    this.websocketsService.blockUser(id);
    const user: User = await this.dataService.getUserByID(id);
    const modalReference = this.ngbModal.open(EditUserModalComponent);
    modalReference.componentInstance.firstname = user.firstName;
    modalReference.componentInstance.lastname = user.lastName;
    modalReference.componentInstance.username = user.username;
    try {
      const result: string[] = await modalReference.result;
      await this.dataService.editUser(result[0], result[1], id);
    } catch (e) {
      console.log('editBtn closed: ' + e);
    }
    this.location.go(this.normalPath);
    this.websocketsService.unblockUser(id);
  }

  async deleteBtn(id: number): Promise<void> {
    const modalReference = this.ngbModal.open(DeleteUserModalComponent);
    modalReference.componentInstance.username = (await this.dataService.getUserByID(id)).username;
    this.websocketsService.blockUser(id);
    try {
      await modalReference.result;
      await this.dataService.deleteUser(id);
    } catch (e) {
      console.log('deleteBtn closed: ' + e);
    }
    this.websocketsService.unblockUser(id);
  }
}

<div class="row ml-3 mr-3">
  <div class="col">
    <table class="table table-striped">
      <thead class="thead-light">
      <tr>
        <th scope="col">#</th>
        <th scope="col">First name</th>
        <th scope="col">Last name</th>
        <th scope="col">Username</th>
        <th scope="col">Description</th>
        <th scope="col">Action</th>
      </tr>
      </thead>
      <tbody *ngFor="let item of dataService.userList; let i = index" id="user-table-body">
      <tr id="userID(${user.id})">
        <td>{{item.id}}</td>
        <td>{{item.firstName}}</td>
        <td>{{item.lastName}}</td>
        <td>{{item.username}}</td>
        <td>{{item.description}}</td>
        <td id="buttons">
          <button (click)="editBtn(item.id)" *ngIf="!item.isBlocked" class="btn btn-sm mr-4">
            <svg class="bi bi-pencil-square" fill="currentColor" height="16" viewBox="0 0 16 16"
                 width="16" xmlns="http://www.w3.org/2000/svg">
              <path
                d="M15.502 1.94a.5.5 0 0 1 0 .706L14.459 3.69l-2-2L13.502.646a.5.5 0 0 1 .707 0l1.293 1.293zm-1.75 2.456-2-2L4.939 9.21a.5.5 0 0 0-.121.196l-.805 2.414a.25.25 0 0 0 .316.316l2.414-.805a.5.5 0 0 0 .196-.12l6.813-6.814z"/>
              <path
                d="M1 13.5A1.5 1.5 0 0 0 2.5 15h11a1.5 1.5 0 0 0 1.5-1.5v-6a.5.5 0 0 0-1 0v6a.5.5 0 0 1-.5.5h-11a.5.5 0 0 1-.5-.5v-11a.5.5 0 0 1 .5-.5H9a.5.5 0 0 0 0-1H2.5A1.5 1.5 0 0 0 1 2.5v11z"
                fill-rule="evenodd"/>
            </svg>
          </button>
          <button (click)="deleteBtn(item.id)" *ngIf="!item.isBlocked" class="btn btn-sm">
            <svg class="bi bi-trash2-fill" fill="currentColor" height="16" viewBox="0 0 16 16" width="16"
                 xmlns="http://www.w3.org/2000/svg">
              <path
                d="M2.037 3.225A.703.703 0 0 1 2 3c0-1.105 2.686-2 6-2s6 .895 6 2a.702.702 0 0 1-.037.225l-1.684 10.104A2 2 0 0 1 10.305 15H5.694a2 2 0 0 1-1.973-1.671L2.037 3.225zm9.89-.69C10.966 2.214 9.578 2 8 2c-1.58 0-2.968.215-3.926.534-.477.16-.795.327-.975.466.18.14.498.307.975.466C5.032 3.786 6.42 4 8 4s2.967-.215 3.926-.534c.477-.16.795-.327.975-.466-.18-.14-.498-.307-.975-.466z"/>
            </svg>
          </button>
          <svg *ngIf="item.isBlocked" class="bi bi-lock-fill" fill="currentColor" height="16" viewBox="0 0 16 16"
               width="16"
               xmlns="http://www.w3.org/2000/svg">
            <path
              d="M8 1a2 2 0 0 1 2 2v4H6V3a2 2 0 0 1 2-2zm3 6V3a3 3 0 0 0-6 0v4a2 2 0 0 0-2 2v5a2 2 0 0 0 2 2h6a2 2 0 0 0 2-2V9a2 2 0 0 0-2-2z"/>
          </svg>
        </td>
      </tr>
      </tbody>
    </table>
  </div>
</div>
