// Übung 3/vue-usermanager/src/App.vue
<template>
  <div id="app">
    <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
      <div class="container-fluid">
        <div class="row container-fluid">
            <div class="row container-fluid">
                <a class="navbar-brand" href="#">Usermanager</a>
            </div>
        </div>
      </div>
    </nav>
    <div class="container-fluid">
      <div class="row">
    <div class="col-9">
    <user-list v-bind:user-list="userList" v-on:user-delete="deleteUser($event)" v-on:user-edit="editUser($event)"></user-list>
    </div>
    <div class="col-3">
    <create-user v-on:create-user="addUser($event)"></create-user>
  </div>
  </div>
  </div>
  </div>
</template>

<script>
import UserList from "./components/userList";
import CreateUser from "./components/CreateUser";
import {User} from "./User";

export default {
  name: 'App',
  data() {
    return {
      userList: [
        new User("Carl", "Friedrich", "Friederlich"),
        new User("Frieda", "Carlo", "Car-los")
      ],
      userCounter: 2
    }
  },
  methods: {
    addUser: function (user){
      if(user.firstName && user.lastName){
        this.userList.push(new User(user.firstName, user.lastName, user.description));
      }
    },
    editUser: function (user){
      for(let entry of this.userList) {
        if (entry.id === user.id){
          this.$set(this.userList, this.userList.indexOf(entry), user)
        }
      }
    },
    deleteUser: function (user){
      if(confirm('Are you sure you wanna delete ' + user.firstName + ' ' + user.lastName + '?')){
        this.userList.splice(this.userList.indexOf(user), 1);
      }
    }
  },
  components: {
    CreateUser,
    UserList
  }
}
</script>

<style lang="scss">
@import "~@/assets/scss/vendors/bootstrap-vue/index";
#app {
  font-family: Avenir, Helvetica, Arial, sans-serif;
  -webkit-font-smoothing: antialiased;
  -moz-osx-font-smoothing: grayscale;
  text-align: center;
  color: #2c3e50;
  margin-top: 60px;
}
</style>

// Übung 3/react-usermanager/src/App.tsx
import React from 'react';
import './App.css';
import {User} from "./User";
import {Table} from "react-bootstrap";
import {Add} from "./Add";
import {EditModal} from "./EditModal";

class App extends React.Component<{}, { title: string, users: User[], show: boolean, editUser: any }> {
    constructor(props: {}) {
        super(props);
        this.state = {
            show: false,
            editUser: undefined,
            title: 'Usermanager',
            users: [new User("Frieda", "Carlo", "Car-los")]
        }
        this.showEditModal = this.showEditModal.bind(this)
    }

    createUser(user: User){
        this.setState(state => ({
            users: [...state.users, user]
        }))
    }

    showEditModal(user: User){
        this.setState(state => ({
            editUser: user,
            show: true
        }))
    }
    hideUserModal(): void{
        this.setState(state => ({
            show: false
        }))
    }

    editUser(editedUser: User){
        let copy: User[] = [];
        for (let user of this.state.users){
            if (user.id === editedUser.id) {
                copy.push(editedUser);
            } else {
                copy.push(user);
            }
        }
        this.setState({
            users: copy,
            show: false
        })
    }
    deleteUser(user: User) {
        let copy: User[] = [...this.state.users];
        for (let entry of this.state.users){
            if (entry.id === user.id){
                copy.splice(copy.indexOf(entry), 1)
                this.setState(state => ({
                    users: copy
                }))
            }
        }
    }

    render() {
        return (
            <div className="App">
                <header>
                    <nav className="navbar navbar-expand-lg navbar-dark bg-dark">
                        <div className="container-fluid">
                            <div className="row container-fluid">
                                <div className="col">
                                    <a className="navbar-brand" href="#">Usermanager</a>
                                </div>
                            </div>
                        </div>
                    </nav>
                </header>
                <body>
                    <div className="row p-5">
                        <div className="col-9">
                            <List items={this.state.users} onDeleteClicked={(user) => {this.deleteUser(user)}} onEditClicked={(user) => {this.showEditModal(user)}}/>
                        </div>
                        <div className="col-3">
                            <Add onCreate={(user) => {this.createUser(user)}}/>
                        </div>
                    </div>
                    <EditModal user={this.state.editUser} show={this.state.show} onSubmit={(user => {this.editUser(user)})} onClose={() => this.hideUserModal()}/>
                </body>
            </div>
        );
    }
}

function List(props: { items: User[], onEditClicked: (user: User) => void , onDeleteClicked: (user: User) => void}) {
    const rows = props.items.map((user) => (
        <tr key={user.id}>
            <td>{user.id}</td>
            <td>{user.firstName}</td>
            <td>{user.lastName}</td>
            <td>{user.description}</td>
            <td>{user.date}</td>
            <td>
                <button className="btn" onClick={() => props.onEditClicked(user)}>Edit</button>
                <button className="btn" onClick={() => props.onDeleteClicked(user)}>Delete</button>
            </td>
        </tr>
    ));

    return (
        <Table>
            <thead>
            <tr>
                <th>Id</th>
                <th>First Name</th>
                <th>Last Name</th>
                <th>Description</th>
                <th>Creation Date</th>
                <th></th>
            </tr>
            </thead>
            <tbody>
            {rows}
            </tbody>
        </Table>
    )
}

export default App;
