// Uebung_3/userman-vue/src/components/AddUser.vue
<template>
  <div class="container mt-2">
    <div class="row">
      <div class="col">
        <form v-on:submit.prevent="addUser()" id="form">
          <div class="input-group mb-3">
            <div class="input-group-prepend">
              <span class="input-group-text">First name</span>
            </div>
            <input v-model="user.firstName" class="form-control" placeholder="First name" type="text">
            <div class="input-group-prepend">
              <span class="input-group-text">Last name</span>
            </div>
            <input v-model="user.lastName" class="form-control" placeholder="Last name" type="text">
          </div>
          <div class="input-group mb-3">
            <div class="input-group-prepend">
              <span class="input-group-text">Username</span>
            </div>
            <input v-model="user.username" class="form-control" placeholder="Username" type="text">

            <div class="input-group-prepend">
              <span class="input-group-text">Description</span>
            </div>
            <input v-model="user.description" class="form-control" placeholder="Description" type="text">

          </div>
          <div class="input-group mb-3">
            <button class="btn btn-info" type="submit">Add user</button>
          </div>
        </form>
      </div>
    </div>
  </div>
</template>

<script lang="ts">
import {User} from "@/model/User";
import {Component, Inject, Vue} from "vue-property-decorator";
import {DataService} from "@/model/DataService";
import {AlertService} from "@/model/AlertService";

@Component
export default class AddUser extends Vue {

  user: User = new User(0, '', '', '', new Date(), 0, false);
  @Inject("dataService") dataService!: DataService;
  @Inject("alertService") alertService !: AlertService;

  addUser() {
    if (this.user.lastName.trim().length > 0 && this.user.firstName.trim().length > 0 &&
        this.user.username.trim().length > 0) {
      this.dataService.addUser(this.user);
      this.user = new User(0, '', '', '', new Date(), 0, false);
      (document.getElementById("form") as HTMLFormElement).reset();
      this.alertService.add("User added!");
    }
  }
}
</script>

<style scoped>

</style>

// Userman with Angular/src/app/Components/add-user/add-user.component.ts
import {Component, OnInit, ViewChild} from '@angular/core';
import {User} from '../../Model/User';
import {DataService} from '../../Service/data.service';

@Component({
  selector: 'app-add-user',
  templateUrl: './add-user.component.html',
  styleUrls: ['./add-user.component.css']
})
export class AddUserComponent implements OnInit {

  user: User = new User(0, '', '', '', new Date(), 0, false);
  password: string = '';
  description: string = '';

  constructor(private dataService: DataService) {
  }

  ngOnInit(): void {
  }

  addUser() {
    if (this.user.lastName.trim().length > 0 && this.user.firstName.trim().length > 0 &&
      this.user.username.trim().length > 0 && this.password.trim().length > 0) {
      this.dataService.addUser(this.user, this.password, this.description).then();
      (document.getElementById("add-user-form") as HTMLFormElement).reset();
    }
  }

}

<div class="container" id="content">
  <div class="row">
    <div class="col">
      <form id="add-user-form">
        <div class="input-group mb-3">
          <div class="input-group-prepend">
            <span class="input-group-text" id="add-user-first-name">First name</span>
          </div>
          <input [(ngModel)]="user.firstName" aria-describedby="add-user-first-name" aria-label="First name"
                 class="form-control"
                 name="first" placeholder="First name" type="text">
          <div class="input-group-prepend">
            <span class="input-group-text" id="add-user-last-name">Last name</span>
          </div>
          <input [(ngModel)]="user.lastName" aria-describedby="add-user-last-name" aria-label="Last name"
                 class="form-control"
                 name="first" placeholder="Last name" type="text">
        </div>
        <div class="input-group mb-3">
          <div class="input-group-prepend">
            <span class="input-group-text" id="add-username">Username</span>
          </div>
          <input [(ngModel)]="user.username" aria-describedby="add-user-name" aria-label="Username" class="form-control"
                 name="first" placeholder="Username" type="text">
          <div class="input-group-prepend">
            <span class="input-group-text" id="add-password">Password</span>
          </div>
          <input [(ngModel)]="password" aria-describedby="add-password" aria-label="Password" class="form-control"
                 name="first" placeholder="Password" type="password">
        </div>
        <div class="input-group mb-3">
          <div class="input-group-prepend">
            <span class="input-group-text">Description</span>
          </div>
          <input [(ngModel)]="description" aria-describedby="add-description" aria-label="Description"
                 class="form-control"
                 name="first" placeholder="Description" type="text">
        </div>
        <div class="input-group mb-3">
          <button (click)="addUser()" class="btn btn-info" type="submit">Add user</button>
        </div>
      </form>
    </div>
  </div>
</div>
