// userman-vue/src/components/Alert.vue
<template>
  <div>
    <div v-for="(item, index) in alertService.alertList" v-bind:key="index">
      <div class="alert alert-warning alert-dismissible fade show" role="alert">
        {{ item }}
        <button v-on:click="alertService.delete_(index)" aria-label="Close" class="close" data-dismiss="alert" type="button">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
    </div>
  </div>
</template>

<script lang="ts">
import {Component, Inject, Vue} from "vue-property-decorator";
import {AlertService} from "@/model/AlertService";

@Component
export default class Alert extends Vue {
  @Inject("alertService") alertService !: AlertService;
}
</script>

<style scoped>

</style>

// Userman with Angular/src/app/Components/alert/alert.component.ts
import {Component, OnInit} from '@angular/core';
import {AlertService} from '../../Service/alert.service';

@Component({
  selector: 'app-alert',
  templateUrl: './alert.component.html',
  styleUrls: ['./alert.component.css']
})
export class AlertComponent implements OnInit {

  text: string = '';

  constructor(public alertService: AlertService) {
  }

  ngOnInit(): void {
  }

}

<div *ngFor="let item of alertService.alertList; let i = index">
  <div class="alert alert-warning alert-dismissible fade show" role="alert">
    {{item}}
    <button (click)="alertService.delete(i)" aria-label="Close" class="close" data-dismiss="alert" type="button">
      <span aria-hidden="true">&times;</span>
    </button>
  </div>
</div>
