// userman-vue/src/components/EditUserModal.vue
<template>
  <div>
    <b-modal ref="modal" title="Edit User">
      <div class="form-group">
        <label>ID</label>
        <input v-model="id" class="form-control" type="text" disabled>
        <label>Firstname</label>
        <input v-model="firstname" class="form-control" type="text">
        <label>Lastname</label>
        <input v-model="lastname" class="form-control" type="text">
        <label>Description</label>
        <input v-model="description" class="form-control" type="text">
      </div>
      <template #modal-footer>
        <button v-on:click="save()" class="btn btn-primary" type="button">Save changes</button>
        <button v-on:click="close()" class="btn btn-secondary" data-dismiss="modal" type="button">Close
        </button>
      </template>
    </b-modal>
  </div>
</template>

<script lang="ts">
import {Component, Inject, Vue} from "vue-property-decorator";
import {DataService} from "@/model/DataService";
import {AlertService} from "@/model/AlertService";

@Component
export default class EditUserModal extends Vue {

  firstname: string = '';
  lastname: string = '';
  description: string = '';
  id: number = 0;
  @Inject("dataService") dataService!: DataService;
  @Inject("alertService") alertService !: AlertService;

  show() {
    (this.$refs.modal as any).show();
  }

  close() {
    (this.$refs.modal as any).hide();
  }

  save() {
    if (this.lastname.trim().length > 0 && this.firstname.trim().length > 0) {
      this.dataService.editUser(this.firstname, this.lastname, this.id, this.description);
      this.close();
      this.alertService.add("User edited!");
    }
  }
}
</script>

<style scoped>

</style>

// Uebung_2/userman/client/src/app/edit-user-modal/edit-user-modal.component.ts
import {Component, Input, OnInit, ViewChild} from '@angular/core';
import {NgbActiveModal, NgbModal} from "@ng-bootstrap/ng-bootstrap";
import {User} from "../models/user.model";
import {DataService} from "../data.service";

@Component({
  selector: 'edit-user-modal-content',
  template: `
      <div class="modal-header">
        <h5 class="modal-title" id="edit-user-modal-title">Edit user: </h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close" (click)="modal.dismiss('Cross click')">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-body">
        <div class="form-group">
          <input type="hidden" aria-hidden="true" id="edit-id-input">
          <label class="form-label">Firstname</label>
          <input class="form-control" type="text" aria-label="First name" [(ngModel)]="user.firstName">
          <label class="form-label">Lastname</label>
          <input class="form-control" type="text" aria-label="Last name" [(ngModel)]="user.lastName">
        </div>
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-secondary" data-dismiss="modal" (click)="modal.close('Close click')">Close
        </button>
        <button type="submit" class="btn btn-info" (click)="modal.close('Save click')">Save changes
        </button>
      </div>
  `
})
export class EditUserModalContent {
  @Input() user!: User;
  constructor(public modal: NgbActiveModal) {}

}


@Component({
  selector: 'app-edit-user-modal',
  templateUrl: './edit-user-modal.component.html',
  styleUrls: ['./edit-user-modal.component.css']
})
export class EditUserModalComponent implements OnInit {
  @ViewChild('editModal') editModal: any;

  constructor(private modal: NgbModal, private dataService: DataService) { }

  ngOnInit(): void {
  }

  open(user: User){
    const modalRef = this.modal.open(EditUserModalContent);
    modalRef.componentInstance.user = user;
    modalRef.result.then((result) => {
      this.dataService.saveUser(user);
    })
  }
}
